#!/usr/bin/env python3
"""
Task — Simple dataclass for orchestrator task queue.

Purpose:
    Represents a single unit of work generated by the OrchestratorAgent.
    Tasks are plain data — no methods, no framework, no async.

Author: AI-Generated
Created: 2026-03-24
Modified: 2026-03-24
"""

from dataclasses import dataclass


@dataclass
class Task:
    """A single orchestrator-generated task."""

    task_type: str      # check_bulk_source | discover_and_scrape | retry_scrape | change_detection
    priority: int       # lower = higher priority
    pwsid: str | None = None
    utility_name: str | None = None
    state_code: str | None = None
    source_key: str | None = None
    registry_id: int | None = None
    notes: str | None = None
